sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-nanjing.aliyuncs.com
    access-key-id: XXX
    access-key-secret: XXX
    bucket-name: web-cj-tlias
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: XXX
    secret: XXX
