sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-nanjing.aliyuncs.com
#    access-key-id: LTAI5tQMRbnRELt1Bwy9gzFt
#    access-key-secret: 9YijQMZFpYPFb5OuDNTNI4kavjNCVR
    bucket-name: web-cj-tlias
  redis:
    host: localhost
    port: 6379
#  wechat:
#    appid: wxc7f2e27d949c066f
#    secret: 71b56d8e31c9cf465b2c58e105399bcd
